### ISSUE TITLE
libphonenumber library is incomplete

### ISSUE THREAD

**Issue by dbaq** [cwill747/angular-libphonenumber#10]
Hey @cwill747, hope you're doing well.

**Overview of the Issue and Motivation for or Use Case**
Since v0.0.9 and more specifically this commit 195713a3e6573b25e36b0affb25aa41083d95597. I can't use this plugin since you removed some functionalities that I was using (including `phoneUtils.formatE164`).

I naturally tried to used https://raw.githubusercontent.com/nathanhammond/libphonenumber/master/dist/libphonenumber.js directly but `phoneUtils.formatAsTyped` is not defined in that file.

**Angular libphonenumber Version(s)**
0.0.9
**Browsers and Operating System**
is this a problem with all browsers? no
**Suggest a Fix**
- where is this `phoneUtils.formatAsTyped` coming from?
- if you want to keep libphonenumber.js without all the `phoneUtils` export, we should at least be able to use the `libphonenumber.js` from @nathanhammond/libphonenumber to use other functions, no? What do you think?

Thanks for your help.

**Comment by cwill747** [comment]
Hmmmm great point. How would you feel about two different exports from this library? Sort of a .core and a .full. That way you could choose between whether you wanted just what is needed for the directive or the full lib if you wanted it?

**Comment by dbaq** [comment]
That's a great alternative :+1:

**Comment by dbaq** [comment]
hey @cwill747,

Do you think you can do it anytime soon? It is a blocking issue on my side.

Thanks for your help.

**Comment by cwill747** [comment]
Unfortunately I am pretty swamped right now with my day job, might take
me a couple days.

Warm Regards,

Cameron Will cameron@thewills.email

On Tue, Feb 16, 2016, at 11:25 AM, Didier Baquier wrote:

> hey @cwill747[1],
> 
> Do you think you can do it anytime soon? It is a blocking issue on
> my side.
> 
> Thanks for your help.
> 
> — Reply to this email directly or view it on GitHub[2].

Links:
1. https://github.com/cwill747
2. https://github.com/cwill747/angular-libphonenumber/issues/10#issuecomment-184753880

**Comment by cwill747** [comment]
Actually, I had a second - I checked in a libphonenumber.full.js - can you see if that works for you? I'm not going to push a new version right yet.

**Comment by dbaq** [comment]
Sure let me check.

**Comment by dbaq** [comment]
It works perfectly! Thank you.

**Comment by CheeseBurger7** [comment]
Can you show me how you implemented that in you application @dbaq ?
