### ISSUE TITLE
Add ability to get non-formatted number

### ISSUE THREAD

**Issue by onigetoc** [cwill747/angular-libphonenumber#11]
Some time i happen number in the input or i got a virtual keyboard who add number to the input.
How can we trigger this plugin on change?

**Comment by cwill747** [comment]
Hey @onigetoc thanks for the question! A couple questions:

What version of Angular are you using?
What version of this library are you using? 

Could you provide a plnkr where you can reproduce the problem? One to fork from is here - https://plnkr.co/edit/k32xZLSRS47w6TW3auAF?p=preview

What onscreen keyboard software are you using and on what kind of device / OS? I can for example get this library to work fine on Mac OSX with the onscreen keyboard.

**Comment by onigetoc** [comment]
Hi, i did find out, 
For my virtual Keypad to work, i need to push number with ng-click and add number like this: 
`$scope.data.search += getnbr;`
I also create a phone number .filter to find number with or without + ( ) - ect
http://codepen.io/onigetoc/pen/xVbazx

**Comment by cwill747** [comment]
Hmmm maybe I should expose the number without any added symbols in case you needed to access it.

**Comment by onigetoc** [comment]
Yes and i just want to create a better regex to remove the 1 or the +1 at the begining of phone number. because i use my Google contact and sometime number begin with 1 or the +1 and my filter do not find them.  for now i have a basic regex.
`.replace(/[+()-\s]/g, "")` 
 i didn't use a number regex only to work with name search too.

**Comment by cwill747** [comment]
Agreed that could be useful. Added it to the plan for the next release.

On Wed, Mar 16, 2016, at 05:26 PM, Gino wrote:

> Yes and i just want to create a better regex to remove the 1 or the +1
> at the begining of phone number. because i use my Google contact and
> sometime number begin with 1 or the +1 and my filter do not find them.
> for now i have a basic regex.
> .replace(/[+()-\s]/g, "")
> 
>  i didn't use a number regex only to work with name search too.
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub[1]

Links:
1. https://github.com/cwill747/angular-libphonenumber/issues/11#issuecomment-197556094

**Comment by cwill747** [comment]
Done and released in v1.1.0.
