### ISSUE TITLE
Push version up for libphonenumber.full.js

### ISSUE THREAD

**Issue by marandus** [cwill747/angular-libphonenumber#12]
Your current version 0.0.9 does not include the libphonenumber.full.js file, so when you install via bower you do not get that thing. You have to reference the commit directly which is quite dirty imho:

bower install angular-libphonenumber#672c4195a0b95692f94cf73cd6964762171c45f4

Please bump your version up so the current state (including libphonenumber.full.js) can be referenced by bower without dirty hacks.

**Comment by cwill747** [comment]
Done. Version 1.0.0 pushed.

**Comment by marandus** [comment]
Thank you very much.
