### ISSUE TITLE
Angular as a devDependency

### ISSUE THREAD

**Issue by dbaq** [cwill747/angular-libphonenumber#4]
Hi,

thanks for your directive, very useful.  Can the bower.json be changed so that angular is a devDependency not a dependency? I am using your directive with ionic which already import angular, that causes conflict.

Thanks

**Comment by cwill747** [comment]
Great point. I will do so.

**Comment by cwill747** [comment]
Closed by 46f26545c7ba7994d4e4d4df6ce934da9ea45374

**Comment by dbaq** [comment]
thanks :+1:
