### ISSUE TITLE
backspacing problem

### ISSUE THREAD

**Issue by dbaq** [cwill747/angular-libphonenumber#8]
**Overview of the Issue**
When using the singapore country code ("sg") and entering `012345`, the backspace key works fine to remove the 5 but then got stuck and cannot remove `01234`.
<img width="400" alt="screen shot 2016-01-14 at 7 31 23 pm" src="https://cloud.githubusercontent.com/assets/1867703/12344757/a7315d1e-baf5-11e5-9ce2-42a363403aac.png">
<img width="398" alt="screen shot 2016-01-14 at 7 31 33 pm" src="https://cloud.githubusercontent.com/assets/1867703/12344754/9fce79c6-baf5-11e5-8a31-dc2abc41abd0.png">

**Angular Version**: v1.4.3
**Angular libphonenumber Version:** 0.0.7
**Browsers and Operating System:** Able to reproduce on chrome and on mobile devices via cordova
**Reproduce the Error:** just run the basic example with singapore country code, enter 012345 then try to delete.
**Suggest a Fix:** I was not able to isolate the part of the code yet.

Thanks for your help!

**EDIT 1:** By triming the returned value of the clean function, the problem disappears. Replace that line (https://github.com/cwill747/angular-libphonenumber/blob/master/src/phone-number.js#L91) by:

``` diff
-return formattedValue;
+return formattedValue.trim();
```

Before opening a PR, I would like to know your thoughts on the issue and make sure it won't cause any regression. Thanks

**Comment by cwill747** [comment]
Thanks for the report, I will take a look!

On Thu, Jan 14, 2016, at 10:41 PM, Didier Baquier wrote:

> _Overview of the Issue_
> 
> When using the singapore country code ("sg") and entering 012345, the
> backspace key works fine to remove the 5 but then got stuck and cannot
> remove 01234.
> screen shot 2016-01-14 at 7 31 23 pm screen shot 2016-01-14 at 7
> 31 33 pm
> 
> _Angular Version_: v1.4.3 _Angular libphonenumber Version:_ 0.0.7
> _Browsers and Operating System:_ Able to reproduce on chrome and on
> mobile devices via cordova _Reproduce the Error:_ just run the basic
> example with singapore country code, enter 012345 then try to delete.
> _Suggest a Fix:_ I was not able to isolate the part of the code yet.
> 
> Thanks for your help!
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/cwill747/angular-libphonenumber/issues/8

**Comment by dbaq** [comment]
Thanks for the quick answer Cameron. I updated the issue with my findings.

**Comment by cwill747** [comment]
Yeah lemme play around with it some. If it works I'll ask you to open the PR.

**Comment by dbaq** [comment]
hey Cameron,

any updates on this one?

**Comment by cwill747** [comment]
Hey yeah. Your change looks good to me. Do you want to open a PR or do you want me to change it?

**Comment by dbaq** [comment]
Thanks for merging the PR, are you going to push https://github.com/cwill747/angular-libphonenumber/milestones/v0.0.9 anytime soon?

**Comment by cwill747** [comment]
Done!
